/* eslint-disable @typescript-eslint/camelcase */
import {
    requiredCondition,
} from '@togglecorp/faram';
import { ResourceTypeKeys } from '#types';

type Schema = {
    [key in ResourceTypeKeys]: object;
};

const defaultFields = {
    resourceType: [requiredCondition],
    title: [requiredCondition],
    point: [],
    description: [],
    ward: [],
    location: [],
};

const schema: Schema = {
    education: {
        fields: {
            ...defaultFields,
            area: [],
            classroomCount: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasDisasterAwarenessConducted: [],
            hasDisasterCommittee: [],
            hasEvacuationRoute: [],
            hasHealthCenterPsychoCounseling: [],
            hasOpenSpace: [],
            isDesignedFollowingBuildingCode: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledFemaleStudents: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledMaleStudents: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfDifferentlyAbledOtherStudents: [],
            noOfFemaleStudent: [],
            noOfMaleStudent: [],
            noOfOtherStudent: [],
            noOfStudent: [],
            noOfMaleEmployee: [],
            noOfFemaleEmployee: [],
            noOfOtherEmployee: [],
            noOfEmployee: [],
            noOfStudentsFifteenToTwenty: [],
            noOfStudentsLessThanTen: [],
            noOfStudentsMoreThanTwenty: [],
            noOfStudentsTenToFifteen: [],
            operatorType: [],
            phoneNumber: [],
            picture: [],
            providesDisasterEducationToStudent: [],
            startTime: [],
            type: [requiredCondition],
            localAddress: [],
            remarksOnBuildingCode: [],
        },
    },

    health: {
        fields: {
            ...defaultFields,
            hfCode: [],
            title: [],
            authority: [],
            authorityLevel: [],
            ownership: [],
            type: [requiredCondition],
            serviceType: [],
            operationalStatus: [],
            bedCount: [],
            hospitalBedCount: [],
            icuBedCount: [],
            ventilatorBedCount: [],
            hasChildImmunization: [],
            hasTdVaccination: [],
            vaccinationFacility: [],
            hasImnci: [],
            hasGrowthMonitoring: [],
            hasSafeMotherhood: [],
            hasAntenatalCare: [],
            hasPostnatalCare: [],
            birthingCenter: [],
            hasBasicEmergencyObstetricCare: [],
            hasComprehensiveEmergencyObstetricCare: [],
            hasComprehensiveAbortionCare: [],
            hasPostAbortionCare: [],
            familyPlanning: [],
            hasCondomPillsDepoprovera: [],
            hasIucd: [],
            hasImplant: [],
            hasVasectomy: [],
            hasMinilap: [],
            hasOpd: [],
            hasGeneral: [],
            hasPediatric: [],
            hasObsAndGynae: [],
            hasDentalOpd: [],
            hasSurgery: [],
            hasGastrointestinal: [],
            hasCardiac: [],
            hasMental: [],
            hasRespiratory: [],
            hasNephrology: [],
            hasEnt: [],
            hasDermatology: [],
            hasEndocrinology: [],
            hasOncology: [],
            hasNeurology: [],
            hasOphthalmology: [],
            hasTreatementOfTb: [],
            hasTreatementOfMdrTb: [],
            hasTreatementOfLeprosy: [],
            hasTreatementOfMalaria: [],
            hasTreatementOfKalaazar: [],
            hasTreatementOfJapaneseEncephalitis: [],
            hasLaboratoryService: [],
            hasTestHiv: [],
            hasTestMalaria: [],
            hasTestTb: [],
            hasTestKalaazar: [],
            hasUrineRe: [],
            hasStoolRe: [],
            hasGeneralBloodCbc: [],
            hasCulture: [],
            hasHormones: [],
            hasLeprosySmearTest: [],
            hasTestCovidPcr: [],
            hasTestCovidAntigen: [],
            hasVolunteerCounselingTest: [],
            hasPmtct: [],
            hasAntiRetroViralTreatment: [],
            hasDental: [],
            hasInPatient: [],
            hasRadiology: [],
            hasXRay: [],
            hasXRayWithContrast: [],
            hasUltrasound: [],
            hasEchocardiogram: [],
            hasEcg: [],
            hasTrademill: [],
            hasCtScan: [],
            hasMri: [],
            hasEndoscopy: [],
            hasColonoscopy: [],
            hasSurgicalService: [],
            hasCaesarianSection: [],
            hasGastrointestinalSurgery: [],
            hasTraumaSurgery: [],
            hasCardiacSurgery: [],
            hasNeuroSurgery: [],
            hasPlasticSurgery: [],
            hasSpecializedService: [],
            hasIcu: [],
            hasCcu: [],
            hasNicu: [],
            hasMicu: [],
            hasSncu: [],
            hasPicu: [],
            hasCardiacCatheterization: [],
            hasPhysiotherapy: [],
            hasAmbulanceService: [],
            hasExtendedHealthService: [],
            hasGeriatricWard: [],
            hasPharmacy: [],
            hasOcmc: [],
            hasHealthInsurance: [],
            hasSsu: [],
            hasAyurvedaService: [],
            hasCovidClinicService: [],
            hasEmergencyServices: [],
            hasOperatingTheatre: [],
            hasBloodDonation: [],
            hasFreeTreatmentKidneyDialysis: [],
            hasFreeTreatmentKidneyTransplant: [],
            hasFreeTreatmentMedicationAfterKidneyTransplant: [],
            hasFreeTreatmentHeadInjury: [],
            hasFreeTreatmentSpinalInjury: [],
            hasFreeTreatmentAlzheimer: [],
            hasFreeTreatmentCancer: [],
            hasFreeTreatmentHeart: [],
            hasFreeTreatmentParkinson: [],
            hasFreeTreatmentSickleCellAnemia: [],
            noOfEmployee: [],
            noOfMaleEmployee: [],
            noOfFemaleEmployee: [],
            noOfOtherEmployee: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            specialization: [],
            registrationEstDate: [],
            lastRenewalDate: [],
            dateOfValidity: [],
            hasInternetFacility: [],
            isDesignedFollowingBuildingCode: [],
            hasDisableFriendlyInfrastructure: [],
            specifyInfrastructure: [],
            hasHelipad: [],
            hasEvacuationRoute: [],
            hasFocalPerson: [],
            focalPersonName: [],
            focalPersonPhoneNumber: [],
            hasOpenSpace: [],
            areaOfOpenSpace: [],
            hasMedicineStorageSpace: [],
            hasBackupElectricity: [],
            startTime: [],
            endTime: [],
            phoneNumber: [],
            emailAddress: [],
            website: [],
            remarksOnOpeningHours: [],
            localAddress: [],
            picture: [],
        },
    },
    finance: {
        fields: {
            ...defaultFields,
            atm: [],
            bank: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasEvacuationRoute: [],
            isDesignedFollowingBuildingCode: [],
            localAddress: [],
            moneyExchange: [],
            hasOtherServices: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            operatorType: [],
            otherOperatorType: [],
            otherServices: [],
            otherType: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            serviceUsers: [],
            specifyInfrastructure: [],
            startTime: [],
            title: [],
            titleNe: [],
            type: [requiredCondition],
            website: [],

        },
    },
    hotelandrestaurant: {
        fields: {
            ...defaultFields,
            type: [requiredCondition],
            areaOfOpenSpace: [],
            building: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasDisasterMgmtUnit: [],
            hasEmployeeDrrTrained: [],
            hasEvacuationRoute: [],
            hasHelipad: [],
            hasOpenSpace: [],
            isDesignedFollowingBuildingCode: [],
            isDrrRelated: [],
            level: [],
            localAddress: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfEmployeeDrrTrained: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            operatorType: [],
            otherOperatorType: [],
            otherType: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            specifyDisasterMgmtUnit: [],
            specifyInfrastructure: [],
            startTime: [],
            startingDateAd: [],
            title: [],
            titleNe: [],
            website: [],
        },
    },
    communication: {
        fields: {
            ...defaultFields,
            type: [requiredCondition],
            cable: [],
            coverageRadius: [],
            emailAddress: [],
            endTime: [],
            fiber: [],
            frequency: [],
            hasDisableFriendlyInfrastructure: [],
            isp: [],
            localAddress: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            operatorType: [],
            otherInternetTypes: [],
            otherOperatorType: [],
            otherType: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            specifyInfrastructure: [],
            startTime: [],
            title: [],
            titleNe: [],
            towersName: [],
            website: [],
            wireless: [],
        },
    },
    governance: {
        fields: {
            ...defaultFields,
            areaOfOpenSpace: [],
            building: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasDisasterMgmtUnit: [],
            hasEmployeeDrrTrained: [],
            hasEvacuationRoute: [],
            hasHelipad: [],
            hasOpenSpace: [],
            isDesignedFollowingBuildingCode: [],
            isDrrRelated: [],
            level: [],
            localAddress: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfEmployeeDrrTrained: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            operatorType: [],
            otherOperatorType: [],
            otherType: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            specifyDisasterMgmtUnit: [],
            specifyInfrastructure: [],
            startTime: [],
            startingDateAd: [],
            type: [requiredCondition],
            title: [],
            titleNe: [],
            website: [],
        },
    },
    industry: {
        fields: {
            ...defaultFields,
            // type: [requiredCondition],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasEvacuationRoute: [],
            isDesignedFollowingBuildingCode: [],
            localAddress: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            operatorType: [],
            otherOperatorType: [],
            otherType: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            specifyInfrastructure: [],
            startTime: [],
            title: [],
            titleNe: [],
            website: [],
            type: [],
            subtype: [],

        },
    },
    cultural: {
        fields: {
            ...defaultFields,
            areaOfOpenSpace: [],
            capacityOfOpenSpace: [],
            drinkingWater: [],
            emailAddress: [],
            endTime: [],
            hasElectricity: [],
            hasOpenSpace: [],
            hasSleepingFacility: [],
            hasWashFacility: [],
            isDesignedFollowingBuildingCode: [],
            noOfBeds: [],
            localAddress: [],
            noOfCots: [],
            noOfMats: [],
            noOfToilets: [],
            otherFacilities: [],
            otherReligion: [],
            phoneNumber: [],
            picture: [],
            religion: [],
            remarksOnOpeningHours: [],
            specifyWashFacility: [],
            startTime: [],
            title: [],
            titleNe: [],
            toilet: [],
            website: [],
        },
    },
    energy: {
        fields: {
            ...defaultFields,
        },
    },
    openspace: {
        fields: {
            ...defaultFields,
            issue: [],
            currentLanduse: [],
            catchmentArea: [],
            ownership: [],
            elevation: [],
            acessToSite: [],
            specialFeature: [],
            image: [],
            shapeFile: [],
            localAddress: [],

        },
    },
    communityspace: {
        fields: {
            ...defaultFields,
            currentLandUse: [],
            elevation: [],
            address: [],
            ward: [],
            capacity: [],
            totalArea: [],
            usableArea: [],
            coverImage: [],
            shapeFile: [],
            localAddress: [],
        },
    },
    bridge: {
        fields: {
            ...defaultFields,
            type: [requiredCondition],
            condition: [],
            isMotorable: [],
            length: [],
            localAddress: [],
            noOfLanes: [],
            otherType: [],
            picture: [],
            title: [],
            titleNe: [],
            width: [],
            dateOfOperation: [],


        },
    },
    electricity: {
        fields: {
            ...defaultFields,
            capacityInMw: [],
            components: [requiredCondition],
            localAddress: [],
            otherComponents: [],
            phoneNumber: [],
            picture: [],
            promoter: [],
            status: [],
            title: [],
            titleNe: [],


        },
    },
    sanitation: {
        fields: {
            ...defaultFields,
            area: [],
            isPermanent: [],
            localAddress: [],
            noOfCommonToilets: [],
            noOfFemaleToilets: [],
            noOfMaleToilets: [],
            noOfTaps: [],
            noOfToilets: [],
            operatorType: [],
            otherOperatorType: [],
            otherType: [],
            picture: [],
            type: [requiredCondition],
            title: [],
            titleNe: [],


        },
    },
    watersupply: {
        fields: {
            ...defaultFields,
            designedWithBuildingCode: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasEvacuationRoute: [],
            hasTechnicalStaff: [],
            isWaterSupplyOperational: [],
            localAddress: [],
            noOfServiceUsers: [],
            operatorType: [],
            otherOperatorType: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            scale: [requiredCondition],
            specifyInfrastructure: [],
            startTime: [],
            technicalStaffDetail: [],
            title: [],
            titleNe: [],
            website: [],
            placementOfWaterTank: [],
            sourceOfWater: [],
            isElectricityNeededToPumpWater: [],
            tankBuildDate: [],


        },
    },
    helipad: {
        fields: {
            ...defaultFields,
            altitude: [],
            area: [],
            emergencyLand: [],
            focalPersonName: [],
            focalPersonNumber: [],
            followsGuidelines: [],
            gr: [],
            hasRoadAccess: [],
            heliMarkerAvailable: [],
            helipadCondition: [],
            internetFacilityAvailable: [],
            localAddressEn: [],
            localAddressNp: [],
            nightLightingAvailable: [],
            operatingDate: [],
            otherOwnership: [],
            otherSurfaceLevel: [],
            otherSurfaceType: [],
            ownership: [],
            picture: [],
            remarks: [],
            storageFacilityAvailable: [],
            surfaceLevel: [],
            surfaceType: [],
            title: [],
            titleNe: [],
            windDirectionIndicatorAvailable: [],

        },
    },
    airway: {
        fields: {
            ...defaultFields,
            type: [requiredCondition],
            areaOfAirport: [],
            designedWithBuildingCode: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasEvacuationRoute: [],
            hasHumanitarianStagingArea: [],
            localAddress: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            specifyInfrastructure: [],
            startTime: [],
            title: [],
            titleNe: [],
            website: [],


        },
    },
    waterway: {
        fields: {
            ...defaultFields,
            type: [requiredCondition],
            condition: [],
            hasDisableFriendlyInfrastructure: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfEmployee: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            otherType: [],
            specifyInfrastructure: [],
            title: [],
            titleNe: [],
            remarksOnOpeningHours: [],


        },
    },
    roadway: {
        fields: {
            ...defaultFields,
            type: [requiredCondition],
            designedWithBuildingCode: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasDisableFriendlyVehicle: [],
            kindOfVehicle: [],
            localAddress: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            noOfDisableFriendlyVehicle: [],
            noOfEmployee: [],
            noOfFemaleEmployee: [],
            noOfMaleEmployee: [],
            noOfOtherEmployee: [],
            numberOfTransporationFacilityAvailable: [],
            otherTypeWithQuantity: [],
            phoneNumber: [],
            picture: [],
            remarksOnOpeningHours: [],
            specifyInfrastructure: [],
            startTime: [],
            title: [],
            titleNe: [],
            website: [],
            nameAndNoOfDisableFriendlyVehicle: [],


        },
    },
    fireengine: {
        fields: {
            ...defaultFields,
            alternativeContactNumber: [],
            capacityOfFireEngine: [],
            condition: [],
            contactNumber: [],
            driverName: [],
            focalPersonContactNumber: [],
            focalPersonName: [],
            hasSafetyEquipmentEnabled: [],
            name: [],
            numberOfFireEngine: [],
            numberOfTrainedEmployees: [],
            operatorType: [],
            otherOperatorType: [],
            ownership: [],
            picture: [],
            remarks: [],
            serviceSharingMuns: [],
            title: [],
            titleNe: [],
            vehicleNumber: [],
        },
    },
    firefightingapparatus: {
        fields: {
            ...defaultFields,
            alternativeContactNumber: [],
            capacityOfFireEngine: [],
            condition: [],
            contactNumber: [],
            driverName: [],
            focalPersonContactNumber: [],
            focalPersonName: [],
            hasSafetyEquipmentEnabled: [],
            name: [],
            numberOfFireEngine: [],
            numberOfFireBike: [],
            numberOfOtherApparatus: [],
            numberOfTrainedEmployees: [],
            operatorType: [],
            otherOperatorType: [],
            ownership: [],
            picture: [],
            remarks: [],
            serviceSharingMuns: [],
            title: [],
            titleNe: [],
            vehicleNumber: [],
            typeOfApparatus: [],
        },
    },
    evacuationcentre: {
        fields: {
            ...defaultFields,
            capacity: [],
            designedWithBuildingCode: [],
            emailAddress: [],
            endTime: [],
            hasDisableFriendlyInfrastructure: [],
            hasDrinkingWater: [],
            hasFoodPreparationFacility: [],
            hasHandWashingFacility: [],
            hasSleepingFacility: [],
            hasToilet: [],
            localAddress: [],
            noOfFoodPreparationFacility: [],
            noOfHandWashingFacility: [],
            noOfSleepingFacility: [],
            noOfToilets: [],
            operatedBy: [],
            phoneNumber: [],
            picture: [],
            specifyInfrastructure: [],
            startTime: [],
            structure: [],
            title: [],
            titleNe: [],
            useOfEvacuationCenter: [],
            website: [],
            remarksOnOpeningHours: [],
            hasEvacuationRoute: [],
        },
    },
    warehouse: {
        fields: {
            ...defaultFields,
            noOfEmployee: [],
            noOfMaleEmployee: [],
            noOfFemaleEmployee: [],
            noOfOtherEmployee: [],
            noOfDifferentlyAbledFemaleEmployees: [],
            noOfDifferentlyAbledMaleEmployees: [],
            noOfDifferentlyAbledOtherEmployees: [],
            hasDisableFriendlyInfrastructure: [],
            specifyInfrastructure: [],
            startTime: [],
            endTime: [],
            website: [],
            localAddress: [],
            picture: [],
            remarksOnOpeningHours: [],
            address: [],
            focalPersonName: [],
            emailAddress: [],
            phoneNumber: [],
            designation: [],
            remarks: [],
            resourceType: [],
        },
    },

};

export const defaultSchema = {
    fields: defaultFields,
};

export default schema;
