export const epidemicDetails = {
    incidentOn: null,
    reportedOn: null,
    cause: null, // hazard inducer
    loss: null, // get loss id from loss api call
    verified: null,
    approved: null,
    // 'hazard' : 9,   // Default 9 is for Epidemmic
    streetAddress: null, // use local address field
    verificationMessage: null,
    point: {
        type: null,
        coordinates: [
            null, // add long from map
            null, // add lat from map
        ],
    },
    wards: [],

    estimatedLoss: null,
    agricultureEconomicLoss: null,
    infrastructureEconomicLoss: null,
    infrastructureDestroyedCount: null,
    infrastructureDestroyedHouseCount: null,
    infrastructureAffectedHouseCount: null,
    livestockDestroyedCount: null,
    totalInjuredMale: null,
    totalInjuredFemale: null,
    totalInjuredOther: null,
    totalInjuredDisabled: null,
    peopleMissingMaleCount: null,
    peopleMissingFemaleCount: null,
    peopleMissingOtherCount: null,
    peopleMissingDisabledCount: null,
    totalDeadMale: null,
    totalDeadFemale: null,
    totalDeadOther: null,
    totalDeadDisabled: null,
};
export const tableTitleRef = {
    id: 'ID',
    province: 'Province',
    district: 'District',
    municipality: 'Municipality',
    wards: 'Wards',
    dataSource: 'Source',
    streetAddress: 'Street Address',
    longitude: 'Longitude',
    latitude: 'Latitude',
    reportedOn: 'Reported on',
    hazard: 'Hazard',
    cause: 'Hazard Inducer',
    estimatedLoss: 'Total Estimated Loss(NPR)',
    agricultureEconomicLoss: 'Agriculture Economic Loss(NPR)',
    infrastructureEconomicLoss: 'Infrastructure Economic Loss(NPR)',
    infrastructureDestroyedCount: 'Total Infrastructure Destroyed',
    infrastructureDestroyedHouseCount: 'House Destroyed',
    infrastructureAffectedHouseCount: 'House Affected',
    livestockDestroyedCount: 'Total Livestock Destroyed',
    totalInjuredMale: 'Total Injured Male',
    totalInjuredFemale: 'Total Injured Female',
    totalInjuredOther: 'Total Injured Others',
    totalInjuredDisabled: 'Total Injured Disabled',
    peopleMissingMaleCount: 'Total Missing Male',
    peopleMissingFemaleCount: 'Total Missing Female',
    peopleMissingOtherCount: 'Total Missing Other',
    peopleMissingDisabledCount: 'Total Missing Disabled',
    totalDeadMale: 'Total Male Dead',
    totalDeadFemale: 'Total Female Dead',
    totalDeadOther: 'Total Others Dead',
    totalDeadDisabled: 'Total Disabled Dead',
    verified: 'Verified',
    verificationMessage: 'Verification message',
    approved: 'Approved',

};
