import React, { useEffect } from 'react';
import ReactHTMLTableToExcel from 'react-html-table-to-excel';
import styles from './styles.scss';
import Icon from '#rscg/Icon';


const PalikaReportTable = (props) => {
    const { paginationData, tableData, tableHeader,
        tableHeaderDataMatch, submenuId } = props;


    return (
        <div>
            {/* <h1>Responsive Table Example</h1> */}
            <div className={styles.palikaTable}>
                <table id="table-to-xls">
                    <tbody>
                        {submenuId === 1
                            ? (
                                <tr>
                                    {/* {tableData
                                 && tableHeader.map((item, i) => (
                                     <th key={item.i}>{item}</th>
                                 ))} */}
                                    <th>SN</th>
                                    <th>Report Title</th>
                                    <th>Province</th>
                                    <th>District</th>
                                    <th>Municipality</th>
                                    <th>Date of report generated</th>
                                    <th>Last modified date</th>
                                    <th>Report generated by</th>
                                    <th>Action Button</th>
                                </tr>
                            )
                            : (
                                <tr>
                                    {/* {tableData
                             && tableHeader.map((item, i) => (
                                 <th key={item.i}>{item}</th>
                             ))} */}
                                    <th>SN</th>
                                    <th>Report Title</th>
                                    <th>Date of report generated</th>
                                    <th>Last modified date</th>
                                    <th>Report generated by</th>
                                    <th>Action Button</th>
                                </tr>
                            )
                        }

                        {/* {tableData
                             && tableData.map(data => (
                                 <tr key={data.item.id}>
                                     {tableHeaderDataMatch.map(title => (
                                         <td key={title}>
                                             {title === 'province'
                                        || title === 'district'
                                         || title === 'municipality'
                                          || title === 'fiscalYear'
                                                 ? data[title] : String(data.item[title])}

                                         </td>
                                     ))}
                                 </tr>
                             ))} */}
                    </tbody>
                </table>

                {tableData && tableData.length === 0
                && <p className={styles.dataUnavailable}>Data Unavailable</p>

                }
            </div>
            { }
        </div>
    );
};

export default PalikaReportTable;
