/* eslint-disable @typescript-eslint/indent */
/* eslint-disable @typescript-eslint/camelcase */
const ibfHousehold = {
        count: 9223372036854775807,
        next: 'http://bipaddev.yilab.org.np/api/v1/ibf-household/?limit=1000&offset=1000',
        previous: null,
        results: [
                {
                        id: 14023,
                        house_id: 172728032,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3690231,
                                        28.2650245,
                                ],
                        },
                        vulnerability: 2.25,
                        normalized_vulnerability: 2.25,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 3.5,
                        normalized_lack_of_coping_capacity: 3.88888888888889,
                        social: 0.0,
                        economic: 0.75,
                        physical: 1.5,
                        risk_score: 2.86939677415858,
                        normalized_risk_score: 3.52364936603245,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 10.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 0.0,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 3.0,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4836,
                },
                {
                        id: 4184,
                        house_id: 170652630,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3752469,
                                        28.2743352,
                                ],
                        },
                        vulnerability: 2.25,
                        normalized_vulnerability: 2.25,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 2.5,
                        normalized_lack_of_coping_capacity: 2.77777777777778,
                        social: 0.75,
                        economic: 0.0,
                        physical: 1.5,
                        risk_score: 2.56496392001504,
                        normalized_risk_score: 3.14980262473718,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 0.0,
                        house_type: 15.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 2.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4836,
                },
                {
                        id: 14446,
                        house_id: 172731983,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3312775,
                                        28.411391,
                                ],
                        },
                        vulnerability: 3.75,
                        normalized_vulnerability: 3.75,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 3.5,
                        normalized_lack_of_coping_capacity: 3.88888888888889,
                        social: 0.75,
                        economic: 0.0,
                        physical: 3.0,
                        risk_score: 3.40204605797668,
                        normalized_risk_score: 4.17774827913715,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 10.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 0.0,
                        house_type: 30.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58008,
                        ward: 4822,
                },
                {
                        id: 14635,
                        house_id: 172738385,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3035151,
                                        28.290417,
                                ],
                        },
                        vulnerability: 3.0,
                        normalized_vulnerability: 3.0,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 1.5,
                        normalized_lack_of_coping_capacity: 1.66666666666667,
                        social: 0.75,
                        economic: 0.75,
                        physical: 1.5,
                        risk_score: 2.24070237327858,
                        normalized_risk_score: 2.92401773821287,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 0.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 1.0,
                        impact_score_five: null,
                        impact_score_twenty: 4.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4860,
                },
                {
                        id: 14649,
                        house_id: 172738401,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3035405,
                                        28.2947884,
                                ],
                        },
                        vulnerability: 4.75,
                        normalized_vulnerability: 4.75,
                        hazard_and_exposure: 7.25,
                        normalized_hazard_and_exposure: 7.25,
                        lack_of_coping_capacity: 2.5,
                        normalized_lack_of_coping_capacity: 2.77777777777778,
                        social: 0.75,
                        economic: 2.5,
                        physical: 1.5,
                        risk_score: 3.62157822172087,
                        normalized_risk_score: 4.57344055418925,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 45.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 15.0,
                        house_type: 15.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4860,
                },
                {
                        id: 14691,
                        house_id: 172738459,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3049591,
                                        28.2976181,
                                ],
                        },
                        vulnerability: 4.75,
                        normalized_vulnerability: 4.75,
                        hazard_and_exposure: 2.75,
                        normalized_hazard_and_exposure: 2.75,
                        lack_of_coping_capacity: 3.5,
                        normalized_lack_of_coping_capacity: 3.88888888888889,
                        social: 0.75,
                        economic: 2.5,
                        physical: 1.5,
                        risk_score: 3.21561379568981,
                        normalized_risk_score: 3.70354204541322,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 10.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 15.0,
                        house_type: 15.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4860,
                },
                {
                        id: 14817,
                        house_id: 172747842,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3088234,
                                        28.2985834,
                                ],
                        },
                        vulnerability: 3.25,
                        normalized_vulnerability: 3.25,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 1.5,
                        normalized_lack_of_coping_capacity: 1.66666666666667,
                        social: 1.5,
                        economic: 1.75,
                        physical: 0.0,
                        risk_score: 2.44548662325437,
                        normalized_risk_score: 3.00308324985761,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 15.0,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 0.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 2.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4860,
                },
                {
                        id: 15150,
                        house_id: 172766998,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3826458,
                                        28.3008494,
                                ],
                        },
                        vulnerability: 5.5,
                        normalized_vulnerability: 5.5,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 1.5,
                        normalized_lack_of_coping_capacity: 1.66666666666667,
                        social: 0.75,
                        economic: 0.75,
                        physical: 4.0,
                        risk_score: 2.91423834162573,
                        normalized_risk_score: 3.57871528169824,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 3.0,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4844,
                },
                {
                        id: 15151,
                        house_id: 172767000,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3826413,
                                        28.300673,
                                ],
                        },
                        vulnerability: 5.5,
                        normalized_vulnerability: 5.5,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 4.5,
                        normalized_lack_of_coping_capacity: 5.0,
                        social: 0.75,
                        economic: 0.75,
                        physical: 4.0,
                        risk_score: 4.20305899598308,
                        normalized_risk_score: 5.16140057728184,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 30.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 4.0,
                        impact_score_twenty: 4.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4844,
                },
                {
                        id: 15210,
                        house_id: 172767485,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3797125,
                                        28.2957447,
                                ],
                        },
                        vulnerability: 6.25,
                        normalized_vulnerability: 6.25,
                        hazard_and_exposure: 7.25,
                        normalized_hazard_and_exposure: 7.25,
                        lack_of_coping_capacity: 0.5,
                        normalized_lack_of_coping_capacity: 0.555555555555556,
                        social: 1.5,
                        economic: 0.75,
                        physical: 4.0,
                        risk_score: 2.32079441680639,
                        normalized_risk_score: 2.93077068999903,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 45.0,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 0.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 15.0,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 2.0,
                        impact_score_twenty: 2.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4844,
                },
                {
                        id: 15220,
                        house_id: 172767565,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3812913,
                                        28.2970523,
                                ],
                        },
                        vulnerability: 5.5,
                        normalized_vulnerability: 5.5,
                        hazard_and_exposure: 5.0,
                        normalized_hazard_and_exposure: 5.0,
                        lack_of_coping_capacity: 1.5,
                        normalized_lack_of_coping_capacity: 1.66666666666667,
                        social: 0.75,
                        economic: 0.75,
                        physical: 4.0,
                        risk_score: 2.91423834162573,
                        normalized_risk_score: 3.57871528169824,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 3.0,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4844,
                },
                {
                        id: 15750,
                        house_id: 173670323,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.057763,
                                        28.4771568,
                                ],
                        },
                        vulnerability: 7.25,
                        normalized_vulnerability: 7.25,
                        hazard_and_exposure: 2.75,
                        normalized_hazard_and_exposure: 2.75,
                        lack_of_coping_capacity: 7.5,
                        normalized_lack_of_coping_capacity: 8.33333333333333,
                        social: 0.75,
                        economic: 2.5,
                        physical: 4.0,
                        risk_score: 4.77320135468002,
                        normalized_risk_score: 5.49747358715028,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 30.0,
                        involvement_of_family: 10.0,
                        access_to_financial: 10.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 15.0,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 4.0,
                        impact_score_twenty: 4.0,
                        province: 7,
                        district: 67,
                        municipality: 71013,
                        ward: 5381,
                },
                {
                        id: 15734,
                        house_id: 173670292,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.0585515,
                                        28.4764604,
                                ],
                        },
                        vulnerability: 7.25,
                        normalized_vulnerability: 7.25,
                        hazard_and_exposure: 2.75,
                        normalized_hazard_and_exposure: 2.75,
                        lack_of_coping_capacity: 2.0,
                        normalized_lack_of_coping_capacity: 2.22222222222222,
                        social: 1.5,
                        economic: 1.75,
                        physical: 4.0,
                        risk_score: 3.07231682568585,
                        normalized_risk_score: 3.53850159369562,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 0.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 15.0,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 3.0,
                        province: 7,
                        district: 67,
                        municipality: 71013,
                        ward: 5381,
                },
                {
                        id: 16196,
                        house_id: 173678448,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3560702,
                                        28.2245931,
                                ],
                        },
                        vulnerability: 3.75,
                        normalized_vulnerability: 3.75,
                        hazard_and_exposure: 2.75,
                        normalized_hazard_and_exposure: 2.75,
                        lack_of_coping_capacity: 1.5,
                        normalized_lack_of_coping_capacity: 1.66666666666667,
                        social: 0.75,
                        economic: 1.75,
                        physical: 1.25,
                        risk_score: 2.24070237327858,
                        normalized_risk_score: 2.58070028864092,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 0.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 0.0,
                        flood_impact_in_house: 12.5,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 2.0,
                        province: 5,
                        district: 65,
                        municipality: 58005,
                        ward: 4811,
                },
                {
                        id: 16168,
                        house_id: 173678373,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3700494,
                                        28.2320007,
                                ],
                        },
                        vulnerability: 4.5,
                        normalized_vulnerability: 4.5,
                        hazard_and_exposure: 2.75,
                        normalized_hazard_and_exposure: 2.75,
                        lack_of_coping_capacity: 3.5,
                        normalized_lack_of_coping_capacity: 3.88888888888889,
                        social: 0.0,
                        economic: 1.75,
                        physical: 2.75,
                        risk_score: 3.15817979882819,
                        normalized_risk_score: 3.63739317439573,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 10.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 0.0,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 12.5,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58005,
                        ward: 4811,
                },
                {
                        id: 16461,
                        house_id: 173743673,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3425244,
                                        28.2016373,
                                ],
                        },
                        vulnerability: 5.5,
                        normalized_vulnerability: 5.5,
                        hazard_and_exposure: 0.0,
                        normalized_hazard_and_exposure: 0.0,
                        lack_of_coping_capacity: 4.5,
                        normalized_lack_of_coping_capacity: 5.0,
                        social: 0.75,
                        economic: 1.75,
                        physical: 3.0,
                        risk_score: 2.31303250459137,
                        normalized_risk_score: 0.0,
                        historical_impacts_and_damage: 0.0,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 10.0,
                        access_to_financial: 10.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 30.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: null,
                        flood_depth_twenty: 1.0,
                        impact_score_five: null,
                        impact_score_twenty: 2.0,
                        province: 5,
                        district: 65,
                        municipality: 58005,
                        ward: 4814,
                },
                {
                        id: 13552,
                        house_id: 172676704,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3814934,
                                        28.2978099,
                                ],
                        },
                        vulnerability: 7.25,
                        normalized_vulnerability: 7.25,
                        hazard_and_exposure: 7.25,
                        normalized_hazard_and_exposure: 7.25,
                        lack_of_coping_capacity: 5.5,
                        normalized_lack_of_coping_capacity: 6.11111111111111,
                        social: 0.75,
                        economic: 2.5,
                        physical: 4.0,
                        risk_score: 5.42317429557714,
                        normalized_risk_score: 6.8485515809303,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 45.0,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 30.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 10.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 15.0,
                        house_type: 15.0,
                        flood_impact_in_house: 25.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 5.0,
                        impact_score_twenty: 5.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4844,
                },
                {
                        id: 13881,
                        house_id: 172684684,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.293304,
                                        28.4052839,
                                ],
                        },
                        vulnerability: 1.75,
                        normalized_vulnerability: 1.75,
                        hazard_and_exposure: 0.0,
                        normalized_hazard_and_exposure: 0.0,
                        lack_of_coping_capacity: 2.5,
                        normalized_lack_of_coping_capacity: 2.77777777777778,
                        social: 0.75,
                        economic: 1.0,
                        physical: 0.0,
                        risk_score: 1.29812352546278,
                        normalized_risk_score: 0.0,
                        historical_impacts_and_damage: 0.0,
                        vicinity_to_rivers: 0.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 0.0,
                        house_type: 0.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 1.0,
                        impact_score_twenty: 1.0,
                        province: 5,
                        district: 65,
                        municipality: 58008,
                        ward: 4820,
                },
                {
                        id: 13498,
                        house_id: 172676041,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.362706,
                                        28.1890249,
                                ],
                        },
                        vulnerability: 6.0,
                        normalized_vulnerability: 6.0,
                        hazard_and_exposure: 7.25,
                        normalized_hazard_and_exposure: 7.25,
                        lack_of_coping_capacity: 2.5,
                        normalized_lack_of_coping_capacity: 2.77777777777778,
                        social: 0.0,
                        economic: 1.75,
                        physical: 4.25,
                        risk_score: 3.91486764116886,
                        normalized_risk_score: 4.94381546890825,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 45.0,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 0.0,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 30.0,
                        flood_impact_in_house: 12.5,
                        flood_depth_five: null,
                        flood_depth_twenty: 0.0,
                        impact_score_five: null,
                        impact_score_twenty: 3.0,
                        province: 5,
                        district: 65,
                        municipality: 58005,
                        ward: 4841,
                },
                {
                        id: 10607,
                        house_id: 171983418,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.3847654,
                                        28.3083967,
                                ],
                        },
                        vulnerability: 4.25,
                        normalized_vulnerability: 4.25,
                        hazard_and_exposure: 7.25,
                        normalized_hazard_and_exposure: 7.25,
                        lack_of_coping_capacity: 4.5,
                        normalized_lack_of_coping_capacity: 5.0,
                        social: 0.75,
                        economic: 0.75,
                        physical: 2.75,
                        risk_score: 4.24509237438777,
                        normalized_risk_score: 5.36083343578294,
                        historical_impacts_and_damage: 27.5,
                        vicinity_to_rivers: 45.0,
                        access_to_drinking_water: 0.0,
                        early_warning_info_access: 30.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 0.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 12.5,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 4.0,
                        impact_score_twenty: 4.0,
                        province: 5,
                        district: 65,
                        municipality: 58003,
                        ward: 4844,
                },
                {
                        id: 13877,
                        house_id: 172684671,
                        point: {
                                type: 'Point',
                                coordinates: [
                                        81.2925915,
                                        28.4051158,
                                ],
                        },
                        vulnerability: 4.0,
                        normalized_vulnerability: 4.0,
                        hazard_and_exposure: 2.25,
                        normalized_hazard_and_exposure: 2.25,
                        lack_of_coping_capacity: 2.5,
                        normalized_lack_of_coping_capacity: 2.77777777777778,
                        social: 0.75,
                        economic: 1.75,
                        physical: 1.5,
                        risk_score: 2.46621207433047,
                        normalized_risk_score: 2.92401773821287,
                        historical_impacts_and_damage: 0.0,
                        vicinity_to_rivers: 22.5,
                        access_to_drinking_water: 10.0,
                        early_warning_info_access: 0.0,
                        involvement_of_family: 0.0,
                        access_to_financial: 0.0,
                        education_level: 5.0,
                        availability_of_social_security: 10.0,
                        distance_to_safe_shelter: 0.0,
                        number_of_dependent_pop: 7.5,
                        female_headed_household: 0.0,
                        income_source: 10.0,
                        annual_income: 7.5,
                        house_type: 15.0,
                        flood_impact_in_house: 0.0,
                        flood_depth_five: 0.0,
                        flood_depth_twenty: 0.0,
                        impact_score_five: 2.0,
                        impact_score_twenty: 2.0,
                        province: 5,
                        district: 65,
                        municipality: 58008,
                        ward: 4820,
                },
        ],
};

export default ibfHousehold;
