const stationDetail = {
    count: 9223372036854775807,
    next: 'http://bipaddev.yilab.org.np/api/v1/station-location/?limit=1000&offset=1000',
    previous: null,
    results: [
        {
            id: 1,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71013,
            ward: 5376,
        },
        {
            id: 2,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71013,
            ward: 5372,
        },
        {
            id: 3,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71013,
            ward: 5381,
        },
        {
            id: 4,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71013,
            ward: 5382,
        },
        {
            id: 5,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71013,
            ward: 5314,
        },
        {
            id: 6,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71008,
            ward: 5383,
        },
        {
            id: 7,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71008,
            ward: 5384,
        },
        {
            id: 8,
            station: 1,
            province: 7,
            district: 67,
            municipality: 71008,
            ward: 5349,
        },
        {
            id: 9,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58008,
            ward: 4821,
        },
        {
            id: 10,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58008,
            ward: 4822,
        },
        {
            id: 11,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58008,
            ward: 4820,
        },
        {
            id: 12,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58003,
            ward: 4867,
        },
        {
            id: 13,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58003,
            ward: 4823,
        },
        {
            id: 14,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58003,
            ward: 4824,
        },
        {
            id: 15,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58003,
            ward: 4860,
        },
        {
            id: 16,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58003,
            ward: 4844,
        },
        {
            id: 17,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58003,
            ward: 4836,
        },
        {
            id: 18,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4840,
        },
        {
            id: 19,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4809,
        },
        {
            id: 20,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4811,
        },
        {
            id: 21,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4812,
        },
        {
            id: 22,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4813,
        },
        {
            id: 23,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4841,
        },
        {
            id: 24,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4808,
        },
        {
            id: 25,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4847,
        },
        {
            id: 26,
            station: 11,
            province: 5,
            district: 65,
            municipality: 58005,
            ward: 4848,
        },
        {
            id: 27,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 28,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 29,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 30,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 31,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 32,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 33,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4010,
            ward: null,
        },
        {
            id: 34,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4008,
            ward: null,
        },
        {
            id: 35,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4008,
            ward: null,
        },
        {
            id: 36,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4008,
            ward: null,
        },
        {
            id: 37,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4008,
            ward: null,
        },
        {
            id: 38,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4008,
            ward: null,
        },
        {
            id: 39,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4008,
            ward: null,
        },
        {
            id: 40,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 41,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 42,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 43,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 44,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 45,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 46,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 47,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 48,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 49,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 50,
            station: 23,
            province: 1,
            district: 4,
            municipality: 4015,
            ward: null,
        },
        {
            id: 51,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 52,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 53,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 54,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 55,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 56,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 57,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 58,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 59,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 60,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 61,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 62,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 63,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 64,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 65,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 66,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 67,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 68,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 69,
            station: 26,
            province: 5,
            district: 37,
            municipality: 49001,
            ward: null,
        },
        {
            id: 70,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 71,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 72,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 73,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 74,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 75,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 76,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 77,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 78,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 79,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 80,
            station: 16,
            province: 1,
            district: 6,
            municipality: 6001,
            ward: null,
        },
        {
            id: 81,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 82,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 83,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 84,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 85,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 86,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 87,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 88,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 89,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 90,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 91,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 92,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 93,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 94,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15008,
            ward: null,
        },
        {
            id: 95,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 96,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 97,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 98,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 99,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 100,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 101,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 102,
            station: 16,
            province: 2,
            district: 16,
            municipality: 15017,
            ward: null,
        },
        {
            id: 103,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48002,
            ward: null,
        },
        {
            id: 104,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48002,
            ward: null,
        },
        {
            id: 105,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48002,
            ward: null,
        },
        {
            id: 106,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48002,
            ward: null,
        },
        {
            id: 107,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48002,
            ward: null,
        },
        {
            id: 108,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48002,
            ward: null,
        },
        {
            id: 109,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 110,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 111,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 112,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 113,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 114,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 115,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48005,
            ward: null,
        },
        {
            id: 116,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48007,
            ward: null,
        },
        {
            id: 117,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48007,
            ward: null,
        },
        {
            id: 118,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48007,
            ward: null,
        },
        {
            id: 119,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48007,
            ward: null,
        },
        {
            id: 120,
            station: 13,
            province: 5,
            district: 482,
            municipality: 48007,
            ward: null,
        },
        {
            id: 121,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 122,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 123,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 124,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 125,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 126,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 127,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 128,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 129,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57008,
            ward: null,
        },
        {
            id: 130,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57002,
            ward: null,
        },
        {
            id: 131,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57002,
            ward: null,
        },
        {
            id: 132,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57002,
            ward: null,
        },
        {
            id: 133,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57002,
            ward: null,
        },
        {
            id: 134,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57002,
            ward: null,
        },
        {
            id: 135,
            station: 14,
            province: 5,
            district: 66,
            municipality: 57002,
            ward: null,
        },
    ],
};

export default stationDetail;
