export interface Sorted {
    Province?: string;
    District?: string;
    Municipality?: string;
    Ward?: string;
    Year?: string;
    Verified: string;
    Title?: string;
    Description?: string;
    Source?: string;
    Hazard?: string;
    'Hazard Type'?: string;
    'Number of incident'?: number;
    'People death'?: number;
    'People missing'?: number;
    'People injured'?: number;
    'Livestock destroyed'?: number;
    'Incident on'?: string;
    'Total estimated loss (NPR)'?: number;
    'Agriculture economic loss (NPR)'?: number;
    'Infrastructure economic loss (NPR)'?: number;
    'Total infrastructure destroyed'?: number;
    'House destroyed'?: number;
    'House affected'?: number;
    'Total livestock destroyed'?: number;
    'Total - People Death'?: number;
    'Male - People Death'?: number;
    'Female - People Death'?: number;
    'Unknown - People Death'?: number;
    'Disabled - People Death'?: number;
    'Total - People Missing'?: number;
    'Male - People Missing'?: number;
    'Female - People Missing'?: number;
    'Unknown - People Missing'?: number;
    'Disabled - People Missing'?: number;
    'Total - People Injured'?: number;
    'Male - People Injured'?: number;
    'Female - People Injured'?: number;
    'Unknown - People Injured'?: number;
    'Disabled - People Injured'?: number;
}
