/* eslint-disable import/prefer-default-export */
export const TableHeader = () => (
    [{
        id: 1,
        data: [
            {
                category: 'Ward Number',
                categoryNe: 'वडा नम्बर',
                subCategory: [],
                subCategoryNe: [],
                keyHeader: '',
                key: [],
            },
            {
                category: 'Education Attainment',
                categoryNe: 'शिक्षा',

                subCategory: ['Primary', 'Lower Secondary',
                    'SLC or equivalent', 'Intermediate or equivalent',
                    'Bachelor or equivalent',
                    'Masters / Ph.D',
                    'No education',
                    'Other / Non-formal',
                    'Not eligible (less than 5 years of age)',
                    'Unknown'],
                subCategoryNe: ['प्राथमिक तह', 'निम्न माध्यमिक तह',
                    'एसएलसी वा  सो सरह ', 'मध्यामिक वा वा  सो सरह',
                    'स्नातक वा सो सरह ',
                    'मास्टर्स / पीएच.डी',
                    'कुनै शिक्षा प्राप्त नगरेको ',
                    'अन्य अनौपचारिक',
                    'लागु नहुने  (५ वर्ष भन्दा कम उमेर)',
                    'थाहा नभएको '],
                keyHeader: 'educationLevel',
                key: [
                    'primary', 'lowerSecondary', 'slcOrEquivalent',
                    'intermediateOrEquivalent', 'bachelorOrEquivalent',
                    'mastersPhd', 'noEducation', 'otherNonformal', 'notEligible',
                    'unknown',
                ],
            },
            {
                category: 'Migration',
                categoryNe: 'परिवारमा उपस्थिति जनसंख्या',
                subCategory: ['Mostly Present', 'Not present, inside Nepal',
                    'Not present, outside Nepal', 'Not known',
                ],
                subCategoryNe: ['घरमै हुने', 'घरमा ननबस्ने  तर नेपालमा बस्ने',
                    'घरमा नबस्ने, नेपाल बाहिर', 'थाहा नभएको',
                ],
                keyHeader: 'migration',
                key: [
                    'mostlyPresent', 'notPresentInsideNepal', 'notPresentOutsideNepal',
                    'notKnown',
                ],
            },
            {
                category: 'Social Security ',
                categoryNe: 'सामाजिक सुरक्षा लाभ को प्रकारद्वारा वर्गीकृत जनसंख्या',
                subCategory: ['Elder citizen', 'Single women',
                    'Differently able', 'Extinct caste', 'Child security',
                    'Pension', 'Others', 'Not availed', 'Not applicable',
                ],
                subCategoryNe: ['जेष्‍ठ नागरिक', 'एकल महिला',
                    'फरक क्षमता भएको व्यक्ती', 'लोपउन्मुख जाति', 'बाल सुरक्षा',
                    'पेन्सन', 'अन्य', 'पाएको छैन', 'लागु नहुने',
                ],
                keyHeader: 'socialSecurityBenefitAvailed',
                key: [
                    'elderCitizen', 'singleWomen', 'differentlyAble',
                    'extinctCaste', 'childSecurity', 'pension', 'others', 'notAvailed',
                    'notApplicable',
                ],
            },
            {
                category: 'People with Disability ',
                categoryNe: 'अपाङ्गता भएका व्यक्तिहरू',
                subCategory: ['Physical Disabilities', 'Visual Disabilities',
                    'Hearing Disabilities',
                    'Hearing-Visual Disabilities', 'Speaking Disabilities ',
                    'Mental Disabilities',
                    'Intellectual Disabilities', 'Multiple Disabilities ',
                ],
                subCategoryNe: ['शारीरिक अपाङ्गता', 'दृष्टि सम्बन्धी अपाङ्गता',
                    ' सुनाइ सम्बन्धी अपाङ्गता',
                    'श्रवण दृष्टिविहीन अपाङ्गता', 'स्वर र बोलाइ सम्बन्धी अपाङ्गता',
                    ' मानसिक वा मनोसामाजिक अपाङ्गता',
                    ' बौद्धिक अपाङ्गता', 'बहुअपाङ्गता',
                ],
                keyHeader: 'disability',
                key: [
                    'physicalDisabilities', 'visualDisabilities', 'hearingDisabilities',
                    'hearingVisualDisabilities', 'speakingDisabilitiesking', 'mentalDisabilities',
                    'intellectualDisabilities', 'multipleDisabilities',

                ],
            },
            {
                category: 'Major occupation ',
                categoryNe: 'प्रमुख पेशा',
                subCategory: ['Agriculture/livestock farming', 'Daily wage worker',
                    'Business', 'Service', 'Foreign employment ',
                    'Student', 'Other',
                ],
                subCategoryNe: ['कृषि/पशुपालन', 'दैनिक ज्याला मजदुर',
                    'व्यवसाय', 'सेवा', 'वैदेशिक रोजगार',
                    'विद्यार्थी', 'अन्य',
                ],
                keyHeader: 'majorOccupation',
                key: ['agriculture', 'dailyWageWorker',
                    'business', 'service', 'foreignEmployment',
                    'student', 'others',

                ],
            },
        ],
    },
    {
        id: 2,
        data: [
            {
                category: 'Ward Number',
                categoryNe: 'वडा नम्बर',
                subCategory: [],
                subCategoryNe: [],
                keyHeader: '',
                key: [],
            },
            {
                category: 'Household Statistics ',
                categoryNe: 'घरेलु तथ्याङ्क',

                subCategory: ['Female Headed Household', 'Household with Member Aged 60+',
                    'Number of Households with Differently able Individuals'],
                subCategoryNe: ['महिला घरमूली भएको घरधुरी संख्या', '६० वर्ष भन्दा माथी उमेरका सदस्य भएको परिवार',
                    'फरक रूपमा सक्षम व्यक्ति भएका परिवारहरूको संख्या'],
                keyHeader: 'noOfHouseholds',
                key: ['femaleHeadedHouseholds', 'householdWithMemberAged60',
                    'numberOfHouseholdsWithDifferentlyAbleIndividual',
                ],
            },
            {
                category: 'Households Monthly Income ',
                categoryNe: 'घरपरिवारको मासिक आम्दानी',
                subCategory: ['Less than NPR 15,000', 'NPR 15,000 - NPR 30,000',
                    'NPR 30,000 - NPR 60,000', 'NPR 60,000 - NPR 120,000', 'NPR 120,000 - NPR 240,000',
                    'More than NPR 240,000',
                ],
                subCategoryNe: ['रु १५,००० भन्दा कम', 'रु १५,००० - रु ३०,०००',
                    'रु ३०,००० - रु ६०,०००', 'रु ६०,००० - रु १२०,०००', 'रु १२०,००० - रु २४०,०००',
                    'रु २४०,००० भन्दा बढी',
                ],
                keyHeader: 'householdIncome',
                key: ['lessThanNpr15', '15To30',
                    '30To60', '60To120', '120To240', 'moreThan240',
                ],
            },
            {
                category: 'Drinking Water',
                categoryNe: 'पिउने पानी',
                subCategory: ['Pipe Water at Home', 'Deep Boring',
                    'Tube well/Hand pump', 'Covered well', 'Open well',
                    'Ground water', 'River',
                ],
                subCategoryNe: ['घरमा पाइपको धाराको पानी', 'बोरिंग',
                    'ट्यूबवेल/हात पम्प', 'ढाकिएको कुवा', 'खुला कुवा',
                    'जमिनको पानी', 'खोला',
                ],
                keyHeader: 'drinkingWater',
                key: ['pipeWaterAtHome', 'deepBoring',
                    'tubeWellHandPump', 'coveredWell', 'openWell', 'groundWater',
                    'river',
                ],
            },
            {
                category: 'Buildings by number of resident house ',
                categoryNe: 'आवासीय घरको संख्या अनुसार भवनहरू',
                subCategory: ['0', '1',
                    '2', '3', '4 ',
                ],
                subCategoryNe: ['०', '१',
                    '२', '३', '४ ',
                ],
                keyHeader: 'buildingsByResidentHh',
                key: ['0', '1',
                    '2', '4', 'fourMore',
                ],
            },

        ],
    },
    {
        id: 3,
        data: [
            {
                category: 'Ward Number',
                categoryNe: 'वडा नम्बर',
                subCategory: [],
                subCategoryNe: [],
                keyHeader: '',
                key: [],
            },
            {
                category: 'Agriculture Practice',
                categoryNe: 'कृषि अभ्यास',
                subCategory: ['Total Number of Household engaged in Agriculture',
                    'Household having own land for agriculture ', 'Household Raising Livestock For Agriculture Purposes'],
                subCategoryNe: ['कृषिमा संलग्न  कुल परिवार  संख्या',
                    'कृषिका लागि आफ्नै जग्गा भएको घरपरिवार', 'कृषि प्रयोजनका लागि घरायसी पशुपालन'],
                keyHeader: 'agriculturePractice',
                key: ['totalNumberOfHouseholdEngagedInAgriculture', 'householdHavingOwnLandForAgriculture',
                    'householdRaisingLivestockForAgriculturePurposes',
                ],
            },
            {
                category: 'Major Agricultural products',
                categoryNe: 'प्रमुख कृषि उत्पादनहरू',
                subCategory: ['Cereals', 'Oilseeds',
                    'Vegetable crop', 'Spicy crops', 'Cash Crops',

                ],
                subCategoryNe: ['अनाज बाली', 'तिलहन',
                    'तरकारी बाली', 'मसालेदार बाली', 'नगदे बाली',

                ],
                keyHeader: 'majorAgriProducts',
                key: ['cereals', 'oilseeds',
                    'vegetableCrop', 'spicyCrop', 'cashCrop',
                ],
            },
            // {
            //     category: 'Food Production ',
            //     subCategory: ['Less than 3 months', 'More than 3 months',
            //         '7-9 months', '9-12 months',
            //     ],
            // },


        ],
    },
    {
        id: 4,
        data: [
            {
                category: 'Ward Number',
                categoryNe: 'वडा नम्बर',
                subCategory: [],
                subCategoryNe: [],
                keyHeader: '',
                key: [],
            },
            {
                category: 'Buildings by Type of Superstructure',
                categoryNe: 'सुपरस्ट्रक्चरको आधारमा भवनका प्रकार ',

                subCategory: ['Adobe/Mud Construction', 'Bamboo', 'Timber', 'Cement Mortar - Brick',
                    'Cement Mortar - Stone', 'Mud Mortar - Brick',
                    'Mud Mortar - Stone',
                    'RC (Engineered)',
                    'RC (Non-Engineered)', 'Others'],
                subCategoryNe: ['एडोब/मड निर्माण', 'बाँस', 'काठ', 'सिमेन्ट मोर्टार - ईंट्टा',
                    'सिमेन्ट मोर्टार - ढुङ्गा', 'मड मोर्टार-इंटा',
                    'माटो मोर्टार - ढुङ्गा',
                    'RC (इन्जिनियर)',
                    'RC (गैर इन्जिनियर)', 'अन्य'],
                keyHeader: 'buildingType',
                key: ['AdobeMudConstruction', 'bamboo',
                    'timber', 'cementBrick', 'cementStone',
                    'mudBrick', 'mudStone', 'rcEngg', 'rcNonEngg',
                    'other',
                ],
            },
            {
                category: 'Buildings by Type of Foundation',
                categoryNe: 'फाउन्डेशनको प्रकार अनुसार भवनहरू',
                subCategory: ['Bamboo/Timber', 'Cement - Stone/Brick',
                    'Mud Mortar - Stone/Brick', 'RC', 'Others',
                ],
                subCategoryNe: ['बाँस / काठ', 'सिमेन्ट - ढुङ्गा/इट्टा',
                    'माटो मोर्टार - ढुङ्गा / ईंट', 'RC', 'अन्य',
                ],
                keyHeader: 'buildingFoundationType',
                key: ['bambooTimber', 'cement',
                    'mud', 'reinforcedConcrete', 'other',
                ],
            },
        ],
    },
        // {
        //     id: 5,
        //     data: [
        //         {
        //             category: 'Ward Number',
        //             subCategory: [],
        //         },
        //         {
        //             category: 'Landuse Practice',

        //             subCategory: ['Agricultural Land',
        // 'Residential Area', 'Commercial Area', 'Industrial Area',
        //                 'Mines and Minerals area', 'Cultural and Archaeological Area',
        //                 'River and Lake Reservoir',
        //                 'Forest Area', 'Public Use and Open Space Area',
        //                 'Building Materials Excavation Area', 'Others'],
        //         },

        //     ],
        // },

    ]
);
