/* eslint-disable max-len */
export default {
    risk: ['case',
        ['all',
            ['>=', ['get', 'normalized_risk_score'], 6.5],
        ], '#9D3C3D',
        ['all',
            ['>=', ['get', 'normalized_risk_score'], 5.0],
            ['<', ['get', 'normalized_risk_score'], 6.5],
        ], '#C24F34',
        ['all',
            ['>=', ['get', 'normalized_risk_score'], 3.5],
            ['<', ['get', 'normalized_risk_score'], 5.0],
        ], '#EEA541',
        ['all',
            ['>=', ['get', 'normalized_risk_score'], 2.0],
            ['<', ['get', 'normalized_risk_score'], 3.5],
        ], '#799655',
        ['all',
            ['<', ['get', 'normalized_risk_score'], 2.0],
        ], '#489DDA', '#A9A9A9',

    ],
    hazard: ['case',
        ['all',
            ['>=', ['get', 'normalized_hazard_and_exposure'], 6.5],
        ], '#9D3C3D',
        ['all',
            ['>=', ['get', 'normalized_hazard_and_exposure'], 5.0],
            ['<', ['get', 'normalized_hazard_and_exposure'], 6.5],
        ], '#C24F34',
        ['all',
            ['>=', ['get', 'normalized_hazard_and_exposure'], 3.5],
            ['<', ['get', 'normalized_hazard_and_exposure'], 5.0],
        ], '#EEA541',
        ['all',
            ['>=', ['get', 'normalized_hazard_and_exposure'], 2.0],
            ['<', ['get', 'normalized_hazard_and_exposure'], 3.5],
        ], '#799655',
        ['all',
            ['<', ['get', 'normalized_hazard_and_exposure'], 2.0],
        ], '#489DDA', '#A9A9A9',

    ],
    vulnerability: ['case',
        ['all',
            ['>=', ['get', 'normalized_vulnerability'], 6.5],
        ], '#9D3C3D',
        ['all',
            ['>=', ['get', 'normalized_vulnerability'], 5.0],
            ['<', ['get', 'normalized_vulnerability'], 6.5],
        ], '#C24F34',
        ['all',
            ['>=', ['get', 'normalized_vulnerability'], 3.5],
            ['<', ['get', 'normalized_vulnerability'], 5.0],
        ], '#EEA541',
        ['all',
            ['>=', ['get', 'normalized_vulnerability'], 2.0],
            ['<', ['get', 'normalized_vulnerability'], 3.5],
        ], '#799655',
        ['all',
            ['<', ['get', 'normalized_vulnerability'], 2.0],
        ], '#489DDA', '#A9A9A9',

    ],
    lackOfCopingCapacity: ['case',
        ['all',
            ['>=', ['get', 'normalized_lack_of_coping_capacity'], 6.5],
        ], '#9D3C3D',
        ['all',
            ['>=', ['get', 'normalized_lack_of_coping_capacity'], 5.0],
            ['<', ['get', 'normalized_lack_of_coping_capacity'], 6.5],
        ], '#C24F34',
        ['all',
            ['>=', ['get', 'normalized_lack_of_coping_capacity'], 3.5],
            ['<', ['get', 'normalized_lack_of_coping_capacity'], 5.0],
        ], '#EEA541',
        ['all',
            ['>=', ['get', 'normalized_lack_of_coping_capacity'], 2.0],
            ['<', ['get', 'normalized_lack_of_coping_capacity'], 3.5],
        ], '#799655',
        ['all',
            ['<', ['get', 'normalized_lack_of_coping_capacity'], 2.0],
        ], '#489DDA', '#A9A9A9',

    ],
    historicalImpactsAndDamage: ['case',
        ['all',
            ['==', ['get', 'hasHouseDamage'], true],
            ['==', ['get', 'hasLossOfFamilyMembers'], true],
            ['==', ['get', 'hasLivelihoodAffect'], true],
        ], '#9D3C3D',
        ['any',
            ['==', ['get', 'hasHouseDamage'], true],
            ['==', ['get', 'hasLossOfFamilyMembers'], true],
            ['==', ['get', 'hasLivelihoodAffect'], true],
        ], '#EEA541',
        ['all',
            ['==', ['get', 'hasHouseDamage'], null],
            ['==', ['get', 'hasLossOfFamilyMembers'], null],
            ['==', ['get', 'hasLivelihoodAffect'], null],
        ], '#A9A9A9', '#799655',
    ],
    vicinityToRivers: ['case',
        ['all',
            ['==', ['get', 'vicinityToRivers'], 'Less than 100 m'],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'vicinityToRivers'], '100-500 m'],
        ], '#EEA541',
        ['match', ['get', 'vicinityToRivers'], ['500 m– 1 km', 'More than 1 km'], true, false], '#799655',
        '#A9A9A9',
    ],
    numberOfDependentPop: ['case',
        ['any',
            ['!', ['has', 'numberOfChildren']],
            ['!', ['has', 'numberOfElderly']],
            ['!', ['has', 'numberOfPregnantLactating']],
            ['!', ['has', 'numberOfDisabled']],
        ],
        '#A9A9A9',
        ['==',
            ['+', ['get', 'numberOfChildren'], ['get', 'numberOfElderly'], ['get', 'numberOfPregnantLactating'], ['get', 'numberOfDisabled']], 0,
        ], '#799655',
        ['in',
            ['+', ['get', 'numberOfChildren'], ['get', 'numberOfElderly'], ['get', 'numberOfPregnantLactating'], ['get', 'numberOfDisabled']], ['literal', [1, 2]],
        ], '#EEA541', '#9D3C3D',

    ],
    // numberOfDependentPop: [
    //     'case',
    //     ['any',
    //         ['has', 'numberOfChildren'],
    //         ['has', 'numberOfElderly'],
    //         ['has', 'numberOfPregnantLactating'],
    //         ['has', 'numberOfDisabled'],
    //     ],
    //     '#A9A9A9',
    //     ['==',
    //         ['+', ['coalesce', ['get', 'numberOfChildren', 0], ['get', 'numberOfElderly', 0], ['get', 'numberOfPregnantLactating', 0], ['get', 'numberOfDisabled', 0]], 0],
    //         0,
    //     ],
    //     '#799655',
    //     ['in',
    //         ['+', ['coalesce', ['get', 'numberOfChildren', 0], ['get', 'numberOfElderly', 0], ['get', 'numberOfPregnantLactating', 0], ['get', 'numberOfDisabled', 0]], ['literal', [1, 2]]],
    //         ['literal', [1, 2]],
    //     ],
    //     '#EEA541',
    //     ['in',
    //         ['+', ['coalesce', ['get', 'numberOfChildren', 0], ['get', 'numberOfElderly', 0], ['get', 'numberOfPregnantLactating', 0], ['get', 'numberOfDisabled', 0]], ['literal', [3, 4, 5]]],
    //         ['literal', [3, 4, 5]],
    //     ],
    //     '#9D3C3D',
    //     '#A9A9A9',
    // ],

    femaleHeadedHousehold: ['case',
        ['all',
            ['==', ['get', 'isFemaleHeadedHousehold'], true],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'isFemaleHeadedHousehold'], null],
        ], '#A9A9A9', '#A9A9A9',

    ],
    incomeSource: ['case',
        ['all',
            ['==', ['get', 'incomeSource'], 10],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'incomeSource'], 0],
        ], '#799655', '#A9A9A9',

    ],
    annualIncome: ['case',
        ['all',
            ['==', ['get', 'annualIncome'], 'More than 1 lakh'],
        ], '#799655',
        ['match', ['get', 'annualIncome'], ['40-60 thousand', '60 thousand to 1 lakh'], true, false], '#EEA541',
        ['all',
            ['==', ['get', 'annualIncome'], 'Less than 40 thousand'],
        ], '#9D3C3D', '#A9A9A9',

    ],
    houseType: ['case',
        ['any',
            ['==', ['get', 'houseTypeWall'], 'Local house made of stone, Rural structures – mud, bamboo, bricks, etc.'],
            ['==', ['get', 'houseTypeWall'], 'Local stone-made, Rural structures – mud, bamboo, bricks, etc.'],
        ], '#9D3C3D',
        ['any',
            ['==', ['get', 'houseTypeWall'], 'Made of ordinary bricks, Blocks, Prefave, Metc.al, Zinc sheets etc.'],
            ['==', ['get', 'houseTypeWall'], 'Made of ordinary bricks, Blocks, Prefave, Metal, Zinc sheets, etc.'],
        ], '#EEA541',
        ['all',
            ['==', ['get', 'houseTypeWall'], 'Reinforced, Well-built structure'],
        ], '#799655', '#A9A9A9',

    ],
    floodImpactInHouse: ['case',
        ['match', ['get', 'floodImpactInThirtyYears'], ['5-6 times', '7-8 times', 'More than 8 times'], true, false], '#9D3C3D',
        ['all',
            ['==', ['get', 'floodImpactInThirtyYears'], '3-4 times'],
        ], '#EEA541',
        ['all',
            ['==', ['get', 'floodImpactInThirtyYears'], '1-2 times'],
        ], '#799655', '#A9A9A9',

    ],
    accessToDrinkingWater: ['case',
        ['all',
            ['==', ['get', 'hasAccessToDrinkingWater'], false],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'hasAccessToDrinkingWater'], true],
        ], '#799655', '#A9A9A9',

    ],
    earlyWarningInformationAccess: ['case',
        ['all',
            ['==', ['get', 'hasAccessToEarlyWarningInformation'], false],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'hasAccessToEarlyWarningInformation'], true],
        ], '#799655', '#A9A9A9',

    ],
    involvementOfFamily: ['case',
        ['all',
            ['==', ['get', 'hasInvolvmentToCommunityGroup'], false],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'hasInvolvmentToCommunityGroup'], true],
        ], '#799655', '#A9A9A9',

    ],
    accessToFinancial: ['case',
        ['all',
            ['==', ['get', 'hasAccessToFinancialServices'], false],
        ], '#9D3C3D',
        ['all',
            ['==', ['get', 'hasAccessToFinancialServices'], true],
        ], '#799655', '#A9A9A9',

    ],
    educationLevel: ['case',
        ['all',
            ['==', ['get', 'educationLevel'], 'Illiterate'],
        ], '#9D3C3D',
        ['match', ['get', 'educationLevel'], ['Class 5', 'Graduate', 'Secondary Level'], true, false], '#EEA541',
        ['all',
            ['==', ['get', 'educationLevel'], 'Literate'],
        ], '#799655', '#A9A9A9',

    ],
    availabilityOfSocialSecurity: ['case',
        ['all',
            ['==', ['get', 'hasAvailabilityOfSocialSecurity'], true],
        ], '#799655',
        ['all',
            ['==', ['get', 'hasAvailabilityOfSocialSecurity'], false],
        ], '#9D3C3D', '#A9A9A9',
    ],

    distanceToSafeShelter: ['case',
        ['match', ['get', 'distanceOfSafeShelter'], ['Within 10 minutes', '10 minutes to half an hour'], true, false], '#94C268',
        ['match', ['get', 'distanceOfSafeShelter'], ['Half an hour to 1 hour', 'More than 1 hour'], true, false], '#DCA75B',
        ['all',
            ['==', ['get', 'distanceOfSafeShelter'], null],
        ], '#A9A9A9', '#A9A9A9',
    ],

    impactScore: ['case',
        ['all',
            ['!=', ['typeof', ['get', 'impactScore']], 'number'],
        ], '#808080',
        ['all',
            ['>=', ['get', 'impactScore'], 1.0],
            ['<=', ['get', 'impactScore'], 2.0],
        ], '#85C55B',
        ['all',
            ['>=', ['get', 'impactScore'], 3.0],
            ['<=', ['get', 'impactScore'], 4.0],
        ], '#ADB014',
        ['all',
            ['>=', ['get', 'impactScore'], 5.0],
            ['<=', ['get', 'impactScore'], 9.0],
        ], '#E7A54B',
        ['all',
            ['>=', ['get', 'impactScore'], 10.0],
            ['<=', ['get', 'impactScore'], 15.0],
        ], '#DB4439', '#A9A9A9',
    ],
    exposed: '#A9A9A9',
};

// ['all',
// ['==', ['typeof', ['get', 'impact_score_five']], 'number'],
// ], '#A9A9A9',
