import fireIcon from '#resources/icons/fire.svg';
import floodIcon from '#resources/icons/flood.svg';
import heatwaveIcon from '#resources/icons/heatwave.svg';
import landslideIcon from '#resources/icons/landslide.svg';
import waterIcon from '#resources/icons/water.svg';
import earthquakeIcon from '#resources/icons/earthquake.svg';
import cycloneIcon from '#resources/icons/cyclone.svg';


const initialSiloDomainData = {
    hazardTypes: {
        1: {
            pk: 1,
            title: 'Earthquake',
            icon: earthquakeIcon,
        },
        2: {
            pk: 2,
            title: 'Urban flood',
            icon: floodIcon,
        },
        3: {
            pk: 3,
            title: 'Costal flood',
            icon: floodIcon,
        },
        4: {
            pk: 4,
            title: 'Landslide',
            icon: landslideIcon,
        },
        5: {
            pk: 5,
            title: 'Wildfire',
            icon: fireIcon,
        },
        6: {
            pk: 6,
            title: 'Water scarcity',
            icon: waterIcon,
        },
        7: {
            pk: 7,
            title: 'Extreme heat',
            icon: heatwaveIcon,
        },
        8: {
            pk: 8,
            title: 'Cyclone',
            icon: cycloneIcon,
        },
    },

    adminLevelList: [
        {
            pk: 1,
            title: 'Province',
        },
        {
            pk: 2,
            title: 'District',
        },
        {
            pk: 3,
            title: 'Municipality',
        },
    ],

    geoAreas: {
        1: [
            { pk: 1, title: 'Province 1' },
            { pk: 2, title: 'Janaki Pradesh' },
            { pk: 3, title: 'Province 3' },
            { pk: 4, title: 'Gandaki Pradesh' },
            { pk: 5, title: 'Province 5' },
            { pk: 6, title: 'Karnali Pradesh' },
            { pk: 7, title: 'Sudurpashim Pradesh' },
        ],
        2: [
            { pk: 1, title: 'Bhojpur' },
            { pk: 2, title: 'Dhankuta' },
            { pk: 3, title: 'Ilam' },
            { pk: 4, title: 'Jhapa' },
            { pk: 5, title: 'Khotang' },
            { pk: 6, title: 'Morang' },
            { pk: 7, title: 'Okhaldhunga' },
            { pk: 8, title: 'Panchthar' },
            { pk: 9, title: 'Sankhuwasabha' },
            { pk: 10, title: 'Solukhumbu' },
            { pk: 11, title: 'Sunsari' },
            { pk: 12, title: 'Taplejung' },
            { pk: 13, title: 'Terhathum' },
            { pk: 14, title: 'Udayapur' },
            { pk: 15, title: 'Saptari' },
            { pk: 16, title: 'Siraha' },
            { pk: 17, title: 'Dhanusa' },
            { pk: 18, title: 'Mahottari' },
            { pk: 19, title: 'Sarlahi' },
            { pk: 20, title: 'Bara' },
            { pk: 21, title: 'Parsa' },
            { pk: 22, title: 'Rautahat' },
            { pk: 23, title: 'Sindhuli' },
            { pk: 24, title: 'Ramechhap' },
            { pk: 25, title: 'Dolakha' },
            { pk: 26, title: 'Bhaktapur' },
            { pk: 27, title: 'Dhading' },
            { pk: 28, title: 'Kathmandu' },
            { pk: 29, title: 'Kavrepalanchok' },
            { pk: 30, title: 'Lalitpur' },
            { pk: 31, title: 'Nuwakot' },
            { pk: 32, title: 'Rasuwa' },
            { pk: 33, title: 'Sindhupalchok' },
            { pk: 34, title: 'Chitwan' },
            { pk: 35, title: 'Makwanpur' },
            { pk: 36, title: 'Baglung' },
            { pk: 37, title: 'Gorkha' },
            { pk: 38, title: 'Kaski' },
            { pk: 39, title: 'Lamjung' },
            { pk: 40, title: 'Manang' },
            { pk: 41, title: 'Mustang' },
            { pk: 42, title: 'Myagdi' },
            { pk: 43, title: 'Nawalpur' },
            { pk: 44, title: 'Parbat' },
            { pk: 45, title: 'Syangja' },
            { pk: 46, title: 'Tanahun' },
            { pk: 47, title: 'Kapilvastu' },
            { pk: 48, title: 'Parasi' },
            { pk: 49, title: 'Rupandehi' },
            { pk: 50, title: 'Arghakhanchi' },
            { pk: 51, title: 'Gulmi' },
            { pk: 52, title: 'Palpa' },
            { pk: 53, title: 'Dang' },
            { pk: 54, title: 'Pyuthan' },
            { pk: 55, title: 'Rolpa' },
            { pk: 56, title: 'Eastern Rukum' },
            { pk: 57, title: 'Banke' },
            { pk: 58, title: 'Bardiya' },
            { pk: 59, title: 'Western Rukum' },
            { pk: 60, title: 'Salyan' },
            { pk: 61, title: 'Dolpa' },
            { pk: 62, title: 'Humla' },
            { pk: 63, title: 'Jumla' },
            { pk: 64, title: 'Kalikot' },
            { pk: 65, title: 'Mugu' },
            { pk: 66, title: 'Surkhet' },
            { pk: 67, title: 'Dailekh' },
            { pk: 68, title: 'Jajarkot' },
            { pk: 69, title: 'Kailali' },
            { pk: 70, title: 'Achham' },
            { pk: 71, title: 'Doti' },
            { pk: 72, title: 'Bajhang' },
            { pk: 73, title: 'Bajura' },
            { pk: 74, title: 'Kanchanpur' },
            { pk: 75, title: 'Dadeldhura' },
            { pk: 76, title: 'Baitadi' },
            { pk: 77, title: 'Darchula' },
        ],
        3: [
            { pk: 1, title: 'Kathmandu' },
            { pk: 2, title: 'Pokhara' },
            { pk: 3, title: 'Lalitpur' },
            { pk: 4, title: 'Bharatpur' },
            { pk: 5, title: 'Birgunj' },
            { pk: 6, title: 'Biratnagar' },
            { pk: 7, title: 'Janakpur' },
            { pk: 8, title: 'Ghorahi' },
            { pk: 9, title: 'Hetauda' },
            { pk: 10, title: 'Dhangadhi' },
            { pk: 11, title: 'Tulsipur' },
            { pk: 12, title: 'Itahari' },
            { pk: 13, title: 'Nepalgunj' },
            { pk: 14, title: 'Butwal' },
            { pk: 15, title: 'Dharan' },
            { pk: 16, title: 'Kalaiya' },
            { pk: 17, title: 'Jitpur Simara' },
            { pk: 18, title: 'Mechinagar' },
            { pk: 19, title: 'Budhanilkantha' },
            { pk: 20, title: 'Gokarneshwor' },
            { pk: 21, title: 'Bheemdatta' },
            { pk: 22, title: 'Birendranagar' },
            { pk: 23, title: 'Tilottama' },
            { pk: 24, title: 'Tokha' },
            { pk: 25, title: 'Lahan' },
            { pk: 26, title: 'Triyuga' },
            { pk: 27, title: 'Chandragiri' },
            { pk: 28, title: 'Madhyapur Thimi' },
            { pk: 29, title: 'Siraha' },
            { pk: 30, title: 'Birtamod' },
            { pk: 31, title: 'Bhaktapur' },
            { pk: 32, title: 'Tarakeshor' },
            { pk: 33, title: 'Sundar Haraincha' },
            { pk: 34, title: 'Suryabinayak' },
            { pk: 35, title: 'Godawari' },
            { pk: 36, title: 'Godawari, Seti' },
            { pk: 37, title: 'Barahachhetra' },
            { pk: 38, title: 'Tikapur' },
            { pk: 39, title: 'Kapilvastu' },
            { pk: 40, title: 'Ghodaghodi' },
            { pk: 41, title: 'Lamki Chuha' },
            { pk: 42, title: 'Banganga' },
            { pk: 43, title: 'Damak' },
            { pk: 44, title: 'Lumbini Sanskritik' },
            { pk: 45, title: 'Chandrapur' },
            { pk: 46, title: 'Kohalpur' },
            { pk: 47, title: 'Vyas' },
            { pk: 48, title: 'Ratnanagar' },
            { pk: 49, title: 'Barahathawa' },
            { pk: 50, title: 'Rajbiraj' },
            { pk: 51, title: 'Barbardiya' },
            { pk: 52, title: 'Shivaraj' },
            { pk: 53, title: 'Gulariya' },
            { pk: 54, title: 'Gaushala' },
            { pk: 55, title: 'Bardibas' },
            { pk: 56, title: 'Belbaari' },
            { pk: 57, title: 'Kirtipur' },
            { pk: 58, title: 'Bhadrapur' },
            { pk: 59, title: 'Nagarjun' },
            { pk: 60, title: 'Dudhauli' },
            { pk: 61, title: 'Kamalamai' },
            { pk: 62, title: 'Buddhabhumi' },
            { pk: 63, title: 'Shiva Sataxi' },
            { pk: 64, title: 'Inaruwa' },
            { pk: 65, title: 'Siddharthanagar' },
            { pk: 66, title: 'Pathari Shanischare' },
            { pk: 67, title: 'Kawasoti' },
            { pk: 68, title: 'Krishnanagar' },
            { pk: 69, title: 'Mahalaxmi' },
            { pk: 70, title: 'Kageshwori Manohara' },
            { pk: 71, title: 'Arjundhara' },
            { pk: 72, title: 'Ishworpur' },
            { pk: 73, title: 'Rajapur' },
            { pk: 74, title: 'Ramgram' },
            { pk: 75, title: 'Lalbandi' },
            { pk: 76, title: 'Gaindakot' },
            { pk: 77, title: 'Jaleshwar' },
            { pk: 78, title: 'Nilkantha' },
            { pk: 79, title: 'Baglung' },
            { pk: 80, title: 'Rapti' },
            { pk: 81, title: 'Suryodaya' },
            { pk: 82, title: 'Krishnapur' },
            { pk: 83, title: 'Duhabi' },
            { pk: 84, title: 'Katari' },
            { pk: 85, title: 'Khairhani' },
            { pk: 86, title: 'Bansgadhi' },
            { pk: 87, title: 'Sainamaina' },
            { pk: 88, title: 'Banepa' },
            { pk: 89, title: 'Changunarayan' },
            { pk: 90, title: 'Sunwal' },
            { pk: 91, title: 'Bardghat' },
            { pk: 92, title: 'Ratuwamai' },
            { pk: 93, title: 'Gauriganga' },
            { pk: 94, title: 'Maharajgunj' },
            { pk: 95, title: 'Urlabari' },
            { pk: 96, title: 'Mahagadhimai' },
            { pk: 97, title: 'Bidur' },
            { pk: 98, title: 'Madhyabindu' },
            { pk: 99, title: 'Punarbas' },
            { pk: 100, title: 'Belauri' },
            { pk: 101, title: 'Devdaha' },
            { pk: 102, title: 'Gauradaha' },
            { pk: 103, title: 'Rangeli' },
            { pk: 104, title: 'Bhajani' },
            { pk: 105, title: 'Ramdhuni' },
            { pk: 106, title: 'Waling' },
            { pk: 107, title: 'Golbazar' },
            { pk: 108, title: 'Sunawarshi' },
            { pk: 109, title: 'Garuda' },
            { pk: 110, title: 'Tansen' },
            { pk: 111, title: 'Mirchaiya' },
            { pk: 112, title: 'Simraungadh' },
            { pk: 113, title: 'Manara Shisawa' },
            { pk: 114, title: 'Bedkot' },
            { pk: 115, title: 'Kalyanpur' },
            { pk: 116, title: 'Gorkha' },
            { pk: 117, title: 'Phidim' },
            { pk: 118, title: 'Chaudandigadhi' },
            { pk: 119, title: 'Ilam' },
            { pk: 120, title: 'Shuklagandaki' },
            { pk: 121, title: 'Godaita' },
            { pk: 122, title: 'Lamahi' },
            { pk: 123, title: 'Dhangadimai' },
            { pk: 124, title: 'Diktel Rupakot Majuwagadhi' },
            { pk: 125, title: 'Shuklaphanta' },
            { pk: 126, title: 'Bhangaha' },
            { pk: 127, title: 'Paunauti' },
            { pk: 128, title: 'Gujara' },
            { pk: 129, title: 'Malangwa' },
            { pk: 130, title: 'Chautara Sangachowkgadhi' },
            { pk: 131, title: 'Madhuwan' },
            { pk: 132, title: 'Sabaila' },
            { pk: 133, title: 'Bhanu' },
            { pk: 134, title: 'Hanumannagar Kankalini' },
            { pk: 135, title: 'Dhanushadham' },
            { pk: 136, title: 'Manthali' },
            { pk: 137, title: 'Khadak' },
            { pk: 138, title: 'Melamchi' },
            { pk: 139, title: 'Balara' },
            { pk: 140, title: 'Mithila' },
            { pk: 141, title: 'Putalibaazar' },
            { pk: 142, title: 'Dakneshwari' },
            { pk: 143, title: 'Thakurbaba' },
            { pk: 144, title: 'Surunga' },
            { pk: 145, title: 'Hariwan' },
            { pk: 146, title: 'Gurbhakot' },
            { pk: 147, title: 'Sitganga' },
            { pk: 148, title: 'Bode Barsain' },
            { pk: 149, title: 'Kolhabi' },
            { pk: 150, title: 'Shahidnagar' },
            { pk: 151, title: 'Brindaban' },
            { pk: 152, title: 'Devchuli' },
            { pk: 153, title: 'Kshireshwor Nath' },
            { pk: 154, title: 'Belaka' },
            { pk: 155, title: 'Balawa' },
            { pk: 156, title: 'Kabilasi' },
            { pk: 157, title: 'Kalika' },
            { pk: 158, title: 'Thaha' },
            { pk: 159, title: 'Dullu' },
            { pk: 160, title: 'Ishnath' },
            { pk: 161, title: 'Bheriganga' },
            { pk: 162, title: 'Sandhikharka' },
            { pk: 163, title: 'Rajpur' },
            { pk: 164, title: 'Gadhimai' },
            { pk: 165, title: 'Bagmati' },
            { pk: 166, title: 'Kankai' },
            { pk: 167, title: 'Belkotgadhi' },
            { pk: 168, title: 'Bahudarmai' },
            { pk: 169, title: 'Kushma' },
            { pk: 170, title: 'Loharpatti' },
            { pk: 171, title: 'Besishahar' },
            { pk: 172, title: 'Mahakali' },
            { pk: 173, title: 'Purchaundi' },
            { pk: 174, title: 'Hansapur' },
            { pk: 175, title: 'Kamala' },
            { pk: 176, title: 'Pyuthan' },
            { pk: 177, title: 'Katahariya' },
            { pk: 178, title: 'Palungtar' },
            { pk: 179, title: 'Parsagadhi' },
            { pk: 180, title: 'Shambhunath' },
            { pk: 181, title: 'Panchkhal' },
            { pk: 182, title: 'Madi' },
            { pk: 183, title: 'Sukhipur' },
            { pk: 184, title: 'Paroha' },
            { pk: 185, title: 'Haripur' },
            { pk: 186, title: 'Ganeshman Charnath' },
            { pk: 187, title: 'Galyang' },
            { pk: 188, title: 'Dhankuta' },
            { pk: 189, title: 'Phatuwa Bijayapur' },
            { pk: 190, title: 'Baudhimai' },
            { pk: 191, title: 'Bangad Kupinde' },
            { pk: 192, title: 'Haripurwa' },
            { pk: 193, title: 'Rampur' },
            { pk: 194, title: 'Chhedagad' },
            { pk: 195, title: 'Kanchanrup' },
            { pk: 196, title: 'Parashuram' },
            { pk: 197, title: 'Nagarain' },
            { pk: 198, title: 'Dasharath Chand' },
            { pk: 199, title: 'Nijgadh' },
            { pk: 200, title: 'Madhav Narayan' },
            { pk: 201, title: 'Gaur' },
            { pk: 202, title: 'Pachrauta' },
            { pk: 203, title: 'Bagchaur' },
            { pk: 204, title: 'Saphebagar' },
            { pk: 205, title: 'Shaarda' },
            { pk: 206, title: 'Aathabiskot' },
            { pk: 207, title: 'Mithila Bihari' },
            { pk: 208, title: 'Bheri' },
            { pk: 209, title: 'Beni' },
            { pk: 210, title: 'Bungal' },
            { pk: 211, title: 'Galkot' },
            { pk: 212, title: 'Dipayal Silgadhi' },
            { pk: 213, title: 'Musikot' },
            { pk: 214, title: 'Deumai' },
            { pk: 215, title: 'Pokhariya' },
            { pk: 216, title: 'Musikot' },
            { pk: 217, title: 'Ropla' },
            { pk: 218, title: 'Mandandeupur' },
            { pk: 219, title: 'Bhumikasthan' },
            { pk: 220, title: 'Mai' },
            { pk: 221, title: 'Resunga' },
            { pk: 222, title: 'Mangalsen' },
            { pk: 223, title: 'Bideha' },
            { pk: 224, title: 'Panchapuri' },
            { pk: 225, title: 'Dhulikhel' },
            { pk: 226, title: 'Dewahi Gonahi' },
            { pk: 227, title: 'Letang' },
            { pk: 228, title: 'Shikhar' },
            { pk: 229, title: 'Aurahi' },
            { pk: 230, title: 'Shadanand' },
            { pk: 231, title: 'Bhimeshwar' },
            { pk: 232, title: 'Jaimini' },
            { pk: 233, title: 'Bhimad' },
            { pk: 234, title: 'Rajdevi' },
            { pk: 235, title: 'Khandbari' },
            { pk: 236, title: 'Dhunibeshi' },
            { pk: 237, title: 'Matihani' },
            { pk: 238, title: 'Karjanha' },
            { pk: 239, title: 'Swargadwari' },
            { pk: 240, title: 'Patan' },
            { pk: 241, title: 'Lekbeshi' },
            { pk: 242, title: 'Ramgopalpur' },
            { pk: 243, title: 'Halesi Tuwachung' },
            { pk: 244, title: 'Namobuddha' },
            { pk: 245, title: 'Aathabis' },
            { pk: 246, title: 'Ramechhap' },
            { pk: 247, title: 'Siddhicharan' },
            { pk: 248, title: 'Panchadewal Binayak' },
            { pk: 249, title: 'Chaurjahari' },
            { pk: 250, title: 'Chainpur' },
            { pk: 251, title: 'Bhojpur' },
            { pk: 252, title: 'Narayan' },
            { pk: 253, title: 'Sundarbazar' },
            { pk: 254, title: 'Barhabise' },
            { pk: 255, title: 'Maulapur' },
            { pk: 256, title: 'Phungling' },
            { pk: 257, title: 'Dhorpatan' },
            { pk: 258, title: 'Chamunda Bindrasaini' },
            { pk: 259, title: 'Chapakot' },
            { pk: 260, title: 'Nalgad' },
            { pk: 261, title: 'Bheerkot' },
            { pk: 262, title: 'Shankharapur' },
            { pk: 263, title: 'Mahalaxmi' },
            { pk: 264, title: 'Phalewas' },
            { pk: 265, title: 'Daxinkaali' },
            { pk: 266, title: 'Kamalbazar' },
            { pk: 267, title: 'Madhya Nepal' },
            { pk: 268, title: 'Melauli' },
            { pk: 269, title: 'Jaya Prithvi' },
            { pk: 270, title: 'Pakhribas' },
            { pk: 271, title: 'Shailyashikhar' },
            { pk: 272, title: 'Budhiganga' },
            { pk: 273, title: 'Aamargadhi' },
            { pk: 274, title: 'Mahakali' },
            { pk: 275, title: 'Saptakoshi' },
            { pk: 276, title: 'Solu Dudhkunda' },
            { pk: 277, title: 'Khandachakra' },
            { pk: 278, title: 'Chhayanath Rara' },
            { pk: 279, title: 'Myanglung' },
            { pk: 280, title: 'Chandannath' },
            { pk: 281, title: 'Budhinanda' },
            { pk: 282, title: 'Rainas' },
            { pk: 283, title: 'Tribeni' },
            { pk: 284, title: 'Dharmadevi' },
            { pk: 285, title: 'Panchkhapan' },
            { pk: 286, title: 'Laligurans' },
            { pk: 287, title: 'Badimalika' },
            { pk: 288, title: 'Raskot' },
            { pk: 289, title: 'Tilagufa' },
            { pk: 290, title: 'Jiri' },
            { pk: 291, title: 'Madi' },
            { pk: 292, title: 'Tripura Sundari' },
            { pk: 293, title: 'Thuli Bheri' },
        ],
    },

    incidentPage: {
        incidentList: [
            {
                pk: 1,
                title: 'Landslide blocks Kali Gandaki',
                description: 'Residents living on the banks of the Kali Gandaki River in Gharapjhong Rural Municipality of Mustang were terrified a lot today following a landslide that blocked water flow in the river for hours.',
                cause: 'day-long snowfall and strong wind at night',
                inducer: 'natural', // or artificial
                severity: 'major', // or minor, catastrophic
                source: {
                    name: 'himalayan-times',
                    displayName: 'The Himalayan Times',
                },
                incident_on: 1550427300733,
                event: undefined,
                hazard: 4, // NOTE: landslide
                loss: {
                    estimatedLoss: 200,
                    peoples: [
                        {
                            // count: ?,
                            status: 'missing', // dead, injured or affected
                            name: 'Hari',
                            age: 18,
                            gender: 'male', // or female
                            belowPoverty: true,
                            disabled: false,
                        },
                    ],
                    families: [
                        {
                            // title: ?
                            // count: ?,
                            status: 'evacuated', // relocated, evacuated
                            belowPoverty: true,
                            phoneNumber: '9816754539',
                        },
                    ],
                    infrastructures: [
                        {
                            title: 'Gandaki Bridge',
                            type: {
                                title: 'bridge',
                                description: '',
                            },
                            status: 'affected', // destroyed
                            equipment_value: 1900000,
                            infrastructure_value: 21312433343,
                            beneficiaryOwner: undefined,
                            serviceDisrupted: true,
                            // count: ?
                        },
                    ],
                    livestocks: [
                        {
                            // title: ''
                            type: {
                                title: 'Cow',
                            },
                            status: 'destroyed', // affected
                            count: 13,
                        },
                    ],
                },
                point: [85.300140, 27.700769],
                geoareaName: {
                    palika: 'Mahalaxmi',
                    district: 'Lalitpur',
                    province: 'Province 3',
                },
                /*
                    polygon: ?
                    wards: ?
                    street address: ?
                    detail: ?
                */
            },
            {
                pk: 2,
                title: 'Earthquake destroys half of the highway',
                description: 'Residents living on the banks of',
                cause: 'Fracking around the hilly region',
                inducer: 'artificial', // or artificial
                severity: 'catastropic', // or minor, catastrophic
                source: {
                    name: 'himalayan-space',
                    displayName: 'The Himalayan Space',
                },
                incident_on: 1550081700430,
                event: undefined,
                hazard: 1,
                point: [85.100140, 27.900769],
                geoareaName: {
                    palika: 'Mahalaxmi',
                    district: 'Lalitpur',
                    province: 'Province 3',
                },
            },
            {
                pk: 3,
                title: 'Wildfire in forests around Chitwan',
                description: 'Unreachable roads due to wildfire',
                cause: 'Careless management of fire',
                inducer: 'artificial', // or artificial
                severity: 'minor', // or minor, catastrophic
                source: {
                    name: 'himalayan-times',
                    displayName: 'The Himalayan Times',
                },
                incident_on: 1549563300865,
                event: undefined,
                hazard: 5,
                point: [85.320140, 27.200769],
                geoareaName: {
                    palika: 'Mahalaxmi',
                    district: 'Lalitpur',
                    province: 'Province 3',
                },
            },
            {
                pk: 4,
                title: 'Flooding around Saptakoshi',
                description: 'this is a description',
                cause: 'Large amount of rain during monsoon',
                inducer: 'natural', // or artificial
                severity: 'major', // or minor, catastrophic
                source: {
                    name: 'himalayan-times',
                    displayName: 'The Himalayan Times',
                },
                incident_on: 1549044900073,
                event: undefined,
                hazard: 2,
                point: [85.800140, 27.100769],
                geoareaName: {
                    palika: 'Mahalaxmi',
                    district: 'Lalitpur',
                    province: 'Province 3',
                },
            },
        ],
        filters: {
            faramValues: {},
            faramErrors: {},
            pristine: true,
        },
    },

    dashboardPage: {
        alertList: [
            {
                pk: 1,
                title: '5.6 magnitude earthquake hits Taplejung',
                hazard: 1,
                lat: 27.6257,
                lng: 87.7763,
                alert_on: 1550427300733,
            },
            {
                pk: 2,
                title: 'Pollution level exceeds 150ppm in Kathmandu',
                hazard: 2,
                lat: 27.7172,
                lng: 85.3240,
                alert_on: 1550081700430,
            },
            {
                pk: 3,
                title: 'Avalanche due to heavy rainfall in the Langtang region',
                hazard: 3,
                lat: 28.2063,
                lng: 85.6229,
                alert_on: 1549563300865,
            },
        ],
        filters: {
            faramValues: {},
            faramErrors: {},
            pristine: true,
        },
    },
};

export default initialSiloDomainData;
